def node_require(script) 
  # Resolve script with node to allow for hoisting
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
end

# Load React Native pod helpers
node_require('react-native/scripts/react_native_pods.rb')

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end
# rn_maps_path = '../node_modules/react-native-maps'
# pod 'react-native-maps/Google', :path => rn_maps_path

target 'GroceryApp' do
  
  config = use_native_modules!

  use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :hermes_enabled => true,
    :fabric_enabled => true
  )
# pod 'react-native-maps', :path => '../node_modules/react-native-maps', :modular_headers => true
pod 'GoogleMaps'
# pod 'Google-Maps-iOS-Utils'
# pod 'GoogleMaps', '~> 6.0'

  # pod 'GoogleMaps', '9.3.0'
  

  target 'GroceryAppTests' do
    inherit! :complete
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
    )
  end
end
